#!/usr/bin/env python3
"""Regenerate every index in the library from the papers' frontmatter.

    ./scripts/build-index.py

Writes:

- library/README.md: the whole topic tree, with paper counts.
- <folder>/README.md for every folder under library/: its subfolders with
  counts, then a table of the papers directly in it (title, year, arXiv, summary).

Indexes are never edited by hand: run this after adding, moving or removing a
paper. Folders left with no papers anywhere below them are removed.
"""

from pathlib import Path
from urllib.parse import quote

from paperlib import LIBRARY_DIR, read_paper

HEADER = "<!-- Generated by scripts/build-index.py. Do not edit by hand. -->"


def link(path):
    return quote(str(path))


def cell(text):
    return " ".join(str(text or "").split()).replace("|", "\\|")


def count(folder):
    return sum(1 for p in folder.rglob("*.md") if p.name != "README.md")


def subfolders(folder):
    return sorted(
        d for d in folder.iterdir() if d.is_dir() and d.name != "images" and count(d)
    )


def remove_empty(folder):
    """Delete folders with no papers below them (an index alone doesn't count)."""
    for d in sorted((p for p in folder.rglob("*") if p.is_dir()), reverse=True):
        if d.name == "images" or count(d):
            continue
        for f in d.iterdir():
            if f.name == "README.md":
                f.unlink()
        if d.exists() and not any(d.iterdir()):
            d.rmdir()


def paper_rows(folder):
    rows = []
    for md in sorted(folder.glob("*.md"), key=lambda p: p.name.lower()):
        if md.name == "README.md":
            continue
        meta, _ = read_paper(md)
        title = meta.get("title") or md.stem
        year = str(meta.get("published") or "")[:4]
        arxiv = meta.get("arxiv")
        arxiv_cell = f"[{arxiv}](https://arxiv.org/abs/{arxiv})" if arxiv else ""
        flag = " *(from PDF text)*" if meta.get("source") == "pdf-text" else ""
        rows.append(
            f"| [{cell(title)}]({link(md.name)}){flag} | {year} | {arxiv_cell} "
            f"| {cell(meta.get('summary'))} |"
        )
    return rows


def folder_index(folder):
    rel = folder.relative_to(LIBRARY_DIR)
    lines = [HEADER, "", f"# {rel}", "", f"{count(folder)} papers."]
    subs = subfolders(folder)
    if subs:
        lines += ["", "| Folder | Papers |", "|---|--:|"]
        lines += [f"| [{d.name}/]({link(d.name)}/README.md) | {count(d)} |" for d in subs]
    rows = paper_rows(folder)
    if rows:
        lines += ["", "| Paper | Year | arXiv | Summary |", "|---|---|---|---|"]
        lines += rows
    return "\n".join(lines) + "\n"


def tree(folder, depth=0):
    out = []
    for d in subfolders(folder):
        rel = d.relative_to(LIBRARY_DIR)
        out.append(f"{'  ' * depth}- [{d.name}/]({link(rel)}/README.md) ({count(d)})")
        out += tree(d, depth + 1)
    return out


def main():
    LIBRARY_DIR.mkdir(parents=True, exist_ok=True)
    remove_empty(LIBRARY_DIR)
    for folder in sorted(p for p in LIBRARY_DIR.rglob("*") if p.is_dir()):
        if folder.name == "images":
            continue
        (folder / "README.md").write_text(folder_index(folder), encoding="utf-8")
    total = count(LIBRARY_DIR)
    root = [HEADER, "", "# Library", "", f"{total} papers.", "", *tree(LIBRARY_DIR)]
    (LIBRARY_DIR / "README.md").write_text("\n".join(root) + "\n", encoding="utf-8")
    print(f"build-index: {total} papers indexed")


if __name__ == "__main__":
    main()
