#!/usr/bin/env python3
"""Regenerate every index in the library from the papers' frontmatter.

    ./scripts/build-index.py

Writes:

- library/README.md: the whole topic tree, with paper counts and scopes.
- <folder>/README.md for every folder under library/: its scope, its
  subfolders with counts, a table of the papers directly in it (title, year,
  arXiv, summary), and the papers considered for it but not added.

Every folder declared in catalog/topics.yaml is created, in library/ and under
PDF_ROOT, even while it is empty. Undeclared folders left with no papers below
them are removed. Indexes are never edited by hand: run this after adding,
moving or removing a paper, or after changing the catalog.
"""

from urllib.parse import quote

from paperlib import LIBRARY_DIR, PDF_ROOT, load_skipped, load_topics, read_paper

HEADER = "<!-- Generated by scripts/build-index.py. Do not edit by hand. -->"


def link(path):
    return quote(str(path))


def cell(text):
    return " ".join(str(text or "").split()).replace("|", "\\|")


def count(folder):
    return sum(1 for p in folder.rglob("*.md") if p.name != "README.md")


def rel(folder):
    return folder.relative_to(LIBRARY_DIR).as_posix()


def subfolders(folder, topics):
    return sorted(
        d for d in folder.iterdir()
        if d.is_dir() and d.name != "images" and (count(d) or rel(d) in topics)
    )


def remove_empty(folder, topics):
    """Delete undeclared folders with no papers below them (an index alone doesn't count)."""
    for d in sorted((p for p in folder.rglob("*") if p.is_dir()), reverse=True):
        if d.name == "images" or count(d) or rel(d) in topics:
            continue
        for f in d.iterdir():
            if f.name == "README.md":
                f.unlink()
        if d.exists() and not any(d.iterdir()):
            d.rmdir()


def paper_rows(folder):
    rows = []
    for md in sorted(folder.glob("*.md"), key=lambda p: p.name.lower()):
        if md.name == "README.md":
            continue
        meta, _ = read_paper(md)
        title = meta.get("title") or md.stem
        year = str(meta.get("published") or "")[:4]
        arxiv = meta.get("arxiv")
        arxiv_cell = f"[{arxiv}](https://arxiv.org/abs/{arxiv})" if arxiv else ""
        flag = " *(from PDF text)*" if meta.get("source") == "pdf-text" else ""
        rows.append(
            f"| [{cell(title)}]({link(md.name)}){flag} | {year} | {arxiv_cell} "
            f"| {cell(meta.get('summary'))} |"
        )
    return rows


def skipped_rows(entries):
    rows = []
    for e in sorted(entries, key=lambda e: str(e.get("title")).lower()):
        url = f"https://arxiv.org/abs/{e['arxiv']}" if e.get("arxiv") else e.get("url")
        title = f"[{cell(e.get('title'))}]({url})" if url else cell(e.get("title"))
        rows.append(f"| {title} | {e.get('year') or ''} | {cell(e.get('reason'))} |")
    return rows


def folder_index(folder, topics, skipped):
    name = rel(folder)
    n = count(folder)
    lines = [HEADER, "", f"# {name}", ""]
    if topics.get(name):
        lines += [topics[name], ""]
    lines.append(f"{n} papers." if n else "No papers yet.")
    subs = subfolders(folder, topics)
    if subs:
        lines += ["", "| Folder | Papers | Scope |", "|---|--:|---|"]
        lines += [
            f"| [{d.name}/]({link(d.name)}/README.md) | {count(d)} | {cell(topics.get(rel(d)))} |"
            for d in subs
        ]
    rows = paper_rows(folder)
    if rows:
        lines += ["", "| Paper | Year | arXiv | Summary |", "|---|---|---|---|"]
        lines += rows
    considered = skipped_rows(skipped.get(name, []))
    if considered:
        lines += ["", "## Considered, not added", "",
                  "Listed in `catalog/skipped.yaml`, so they are not proposed again.", "",
                  "| Paper | Year | Why not |", "|---|---|---|"]
        lines += considered
    return "\n".join(lines) + "\n"


def tree(folder, topics, depth=0):
    out = []
    for d in subfolders(folder, topics):
        n = count(d)
        scope = topics.get(rel(d))
        line = f"{'  ' * depth}- [{d.name}/]({link(rel(d))}/README.md) ({n})"
        out.append(f"{line}: {scope}" if scope and depth == 0 else line)
        out += tree(d, topics, depth + 1)
    return out


def main():
    topics = load_topics()
    skipped = {}
    for entry in load_skipped():
        skipped.setdefault(entry.get("topic"), []).append(entry)
    LIBRARY_DIR.mkdir(parents=True, exist_ok=True)
    for topic in topics:
        (LIBRARY_DIR / topic).mkdir(parents=True, exist_ok=True)
        if PDF_ROOT.exists():
            (PDF_ROOT / topic).mkdir(parents=True, exist_ok=True)
    remove_empty(LIBRARY_DIR, topics)
    for folder in sorted(p for p in LIBRARY_DIR.rglob("*") if p.is_dir()):
        if folder.name == "images":
            continue
        (folder / "README.md").write_text(folder_index(folder, topics, skipped), encoding="utf-8")
    total = count(LIBRARY_DIR)
    root = [HEADER, "", "# Library", "", f"{total} papers in {len(topics)} topic folders.", "",
            *tree(LIBRARY_DIR, topics)]
    (LIBRARY_DIR / "README.md").write_text("\n".join(root) + "\n", encoding="utf-8")
    print(f"build-index: {total} papers indexed")


if __name__ == "__main__":
    main()
