"""paperlib init: make a folder a paper library, or refresh one.

    paperlib init [<folder>] [--pdf-root <path>] [--no-skills]

Creates what is missing and leaves what exists alone, so it is safe to run
again (after updating the engine, or on another machine):

- paper-library.yaml, the library's config (--pdf-root sets where PDFs go);
- library/, catalog/topics.yaml, catalog/skipped.yaml, notes/, reviews/,
  INBOX.txt;
- AGENTS.md (the reader's own instructions, importing the generated guide) and
  CLAUDE.md, which points Claude Code at AGENTS.md;
- .claude/skills/<name>: a symlink to each of the engine's skills, so Claude
  Code opened on the library has them and engine edits show up at once;
- the PDF link named by `pdf_link:` (default pdf/), a symlink to the PDF root,
  so an editor opened on the library shows the PDFs next to the markdown;
- .vscode/settings.json for the PDF viewer, and .gitignore entries for the
  links;
- then builds the indexes and the guide.
"""

import json
import os
import subprocess
import sys
from pathlib import Path

ENGINE = Path(__file__).resolve().parent.parent

CONFIG_TEMPLATE = """\
# Paper library configuration, read by agentic-paper-library (paperlib).
# Relative paths are taken from this file's folder; ~ is expanded.

# Who reads this library; the skills address notes and questions to them.
reader: {reader}

# Where the original PDFs go, mirroring library/ (outside git; a synced
# folder works well for reading them on a tablet).
pdf_root: {pdf_root}

# A symlink in this folder to pdf_root, so an editor shows both trees and the
# indexes link each paper's PDF. Remove the line to turn both off.
pdf_link: pdf

# Optional: a folder for the reader's own note per paper (the overview skill
# writes there), e.g. in an Obsidian vault.
# overview_dir: ~/obsidian/Papers

# Defaults, change only to rename:
# library: library
# catalog: catalog
# notes: notes
# reviews: reviews
# inbox: INBOX.txt
# cache: ~/.cache/papers      # arXiv downloads, shared by every library
# chrome: /path/to/chrome     # for web articles, when not found on PATH
"""

AGENTS_TEMPLATE = """\
# Working in this library

<!-- Your own instructions for the agent: who reads this library and why,
what to focus on, how you like papers explained. The engine's conventions are
imported below and regenerated by `paperlib build-index`; don't edit that file. -->

## Reader

{reader}'s research-paper library.

## Explaining papers

Lead with the intuition and a concrete example before the formalism; restate
heavy notation in plain terms. Say what is new compared with papers already in
the library, and give page numbers for anything worth looking up in the PDF.

@.claude/library-guide.md
"""

GITIGNORE = ["*.pdf", ".DS_Store", ".claude/skills/", "reviews/.work/"]


def write_new(path, text):
    if path.exists():
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print(f"  created {path.relative_to(Path.cwd()) if path.is_relative_to(Path.cwd()) else path}")
    return True


def symlink(link, target):
    """Point `link` at `target`; replace a stale symlink, never a real file."""
    if link.is_symlink():
        if Path(os.readlink(link)) == target:
            return
        link.unlink()
    elif link.exists():
        print(f"  left alone: {link} exists and is not a symlink")
        return
    link.parent.mkdir(parents=True, exist_ok=True)
    link.symlink_to(target, target_is_directory=target.is_dir())
    print(f"  linked {link} -> {target}")


def main(argv):
    if "-h" in argv or "--help" in argv:
        print(__doc__)
        return 0
    pdf_root, skills, folder = None, True, None
    args = list(argv)
    while args:
        a = args.pop(0)
        if a == "--pdf-root":
            pdf_root = args.pop(0)
        elif a == "--no-skills":
            skills = False
        else:
            folder = a
    root = Path(folder or ".").expanduser().absolute()
    root.mkdir(parents=True, exist_ok=True)
    root = root.resolve()
    os.chdir(root)
    print(f"paperlib init: {root}")

    reader = os.environ.get("USER", "the reader").capitalize()
    write_new(root / "paper-library.yaml",
              CONFIG_TEMPLATE.format(reader=reader, pdf_root=pdf_root or "pdfs"))
    os.environ["PAPER_LIBRARY"] = str(root)
    import paperlib  # reads the config just written

    for d in (paperlib.LIBRARY_DIR, paperlib.NOTES_DIR, paperlib.REVIEWS_DIR, paperlib.PDF_ROOT):
        d.mkdir(parents=True, exist_ok=True)
    write_new(paperlib.TOPICS_FILE, "# Every topic folder, with its scope: <path>: <scope>\n{}\n")
    write_new(paperlib.SKIPPED_FILE, "# Papers deliberately not added: title, reason, date.\n[]\n")
    write_new(paperlib.INBOX_FILE, "")
    write_new(root / "AGENTS.md", AGENTS_TEMPLATE.format(reader=paperlib.CONFIG.get("reader", reader)))
    write_new(root / "CLAUDE.md", "@AGENTS.md\n")

    if skills:
        for skill in sorted((ENGINE / "skills").iterdir()):
            if (skill / "SKILL.md").exists():
                symlink(root / ".claude" / "skills" / skill.name, skill)
    if paperlib.PDF_LINK_DIR and not paperlib.PDF_ROOT.resolve().is_relative_to(root):
        symlink(paperlib.PDF_LINK_DIR, paperlib.PDF_ROOT)

    vscode = root / ".vscode" / "settings.json"
    settings = json.loads(vscode.read_text()) if vscode.exists() else {}
    pdfs = paperlib.PDF_ROOT
    home = Path.home()
    wanted = {
        "pdfViewer.pdfRoot": "~/" + pdfs.relative_to(home).as_posix() if pdfs.is_relative_to(home) else str(pdfs),
        # .gitignore keeps the PDFs out of git, but they should show in quick open and
        # search, so VS Code is told not to apply it; what it hid is excluded here instead.
        "search.useIgnoreFiles": False,
        "search.exclude": {"**/images": True, ".claude/skills": True, "reviews/.work": True,
                           "**/.DS_Store": True},
        "git.ignoreLimitWarning": True,
    }
    added = {k: v for k, v in wanted.items() if k not in settings}
    if added:
        settings.update(added)
        vscode.parent.mkdir(exist_ok=True)
        vscode.write_text(json.dumps(settings, indent=2) + "\n", encoding="utf-8")
        print(f"  set {', '.join(added)} in .vscode/settings.json")

    gitignore = root / ".gitignore"
    lines = gitignore.read_text().splitlines() if gitignore.exists() else []
    wanted_lines = GITIGNORE + ([f"/{paperlib.PDF_LINK_DIR.name}"] if paperlib.PDF_LINK_DIR else [])
    missing = [l for l in wanted_lines if l not in lines]
    if missing:
        gitignore.write_text("\n".join(lines + missing) + "\n", encoding="utf-8")
        print(f"  ignored {', '.join(missing)}")

    sys.stdout.flush()
    env = dict(os.environ, PATH=str(Path(sys.executable).parent) + os.pathsep + os.environ["PATH"])
    return subprocess.run([sys.executable, str(ENGINE / "scripts" / "build-index.py")], env=env).returncode
