#!/usr/bin/env python3
"""Turn a review's links to papers into reference-style links.

    ./scripts/review-refs.py             every review
    ./scripts/review-refs.py <scope>     one review
    ./scripts/review-refs.py --inline [<scope>]   the reverse: write every link inline

A review links each paper and each cited page many times, and the encoded paths
are long, so inline links bury the prose. This rewrites

    [MMLU](../../library/llm/evaluation/benchmarks/Measuring%20Massive….md)
    [p. 5, Table 1](http://pdf.invalid/llm/…/Measuring%20Massive….pdf?dest=table.1&page=5)

as

    [MMLU][measuring-massive-multitask-language]
    [p. 5, Table 1][measuring-massive-multitask-language@5:table.1]

and puts the definitions in one block at the end of the file. A paper's label
is made from its filename: its name when the title has one ("MMLU-Pro. A More
Robust…" gives "mmlu-pro"), else its first four words, with more words added
when two papers in the review would share a label. A page link's label adds
"@<page>", then ":<dest>" if it has one. Only links to papers and to
places in their PDFs are converted: links to other reviews, folders and images
stay inline.

Run it after writing or editing a review; links may be written inline or
reference-style, in any mix. It is idempotent: the file is first read with all
its references resolved, then written again from scratch.
"""

import hashlib
import re
import sys
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlsplit

from paperlib import (
    LIBRARY_DIR, LIBRARY_ROOT, PDF_LINK_BASE, REF_DEF, link_definitions, load_reviews,
)

MARKER = "<!-- Link definitions, generated by `paperlib review-refs`. Do not edit by hand. -->"
FENCE = re.compile(r"^(```|~~~).*?^\1[ \t]*$", re.M | re.S)
INLINE = re.compile(r"(?<!\!)\[((?:\\.|[^\]\\])*)\]\(([^)\s]+)\)")
REFERENCE = re.compile(r"(?<!\!)\[((?:\\.|[^\]\\])*)\]\[([^\]\n]+)\]")


def outside_fences(text, fn):
    """Apply fn to the parts of text that are not in a fenced code block."""
    out, last = [], 0
    for m in FENCE.finditer(text):
        out += [fn(text[last:m.start()]), m.group(0)]
        last = m.end()
    return "".join(out + [fn(text[last:])])


def to_inline(text):
    """The text with every reference-style link written inline and no definitions."""
    definitions = link_definitions(text)
    text = REF_DEF.sub("", text).replace(MARKER, "")

    def expand(m):
        target = definitions.get(m.group(2).lower())
        return f"[{m.group(1)}]({target})" if target else m.group(0)

    return outside_fences(text, lambda part: REFERENCE.sub(expand, part)).rstrip() + "\n"


def words_of(text):
    found = re.findall(r"[^\W_]+(?:['’][^\W_]+)?", text.replace("^", ""))
    return [w.replace("'", "").replace("’", "").lower() for w in found]


def slug(stem, extra=0):
    """A label from a filename stem: the paper's name when the title has one
    ("MMLU-Pro. A More Robust…" gives "mmlu-pro"), else its first four words;
    `extra` more words are added to tell two papers apart."""
    name = words_of(stem.split(". ")[0])
    base = len(name) if ". " in stem and len(name) <= 5 else min(4, len(name))
    return "-".join(words_of(stem)[:base + extra])


def paper_of(target, review):
    """(paper stem, query) if the target is a paper or a place in its PDF, else None."""
    if target.startswith(PDF_LINK_BASE):
        parts = urlsplit(target)
        return Path(unquote(parts.path)).stem, parts.query
    if re.match(r"^[a-z]+:", target) or target.startswith("#") or not target.endswith(".md"):
        return None
    resolved = (review.parent / unquote(target)).resolve()
    if LIBRARY_DIR.resolve() in resolved.parents and resolved.name != "README.md":
        return resolved.stem, None
    return None


def page_suffix(query):
    q = parse_qs(query)
    out = "@" + q.get("page", ["?"])[0]
    if "dest" in q:
        out += ":" + q["dest"][0]
    if "search" in q:
        out += "~" + hashlib.sha1(q["search"][0].encode()).hexdigest()[:4]
    return out


def to_references(text, review):
    """The text with links to papers reference-style and one block of definitions."""
    text = to_inline(text)
    stems = sorted({p[0] for _, t in INLINE.findall(FENCE.sub("", text))
                    if (p := paper_of(t, review))})
    # The shortest label that tells this review's papers apart.
    labels = {}
    for stem in stems:
        extra = 0
        while sum(slug(s, extra) == slug(stem, extra) for s in stems) > 1 and extra < 40:
            extra += 1
        labels[stem] = slug(stem, extra)
    definitions = {}

    def refer(m):
        paper = paper_of(m.group(2), review)
        if not paper:
            return m.group(0)
        label = labels[paper[0]] + (page_suffix(paper[1]) if paper[1] is not None else "")
        if definitions.setdefault(label, m.group(2)) != m.group(2):
            return m.group(0)  # two different targets would share the label: leave inline
        return f"[{m.group(1)}][{label}]"

    text = outside_fences(text, lambda part: INLINE.sub(refer, part))
    if not definitions:
        return text
    block = "\n".join(f"[{label}]: {target}" for label, target in sorted(definitions.items()))
    return f"{text.rstrip()}\n\n{MARKER}\n\n{block}\n"


def main(argv):
    inline = "--inline" in argv
    scopes = [a.strip("/") for a in argv if not a.startswith("-")]
    if len(scopes) > 1 or any(a.startswith("-") and a != "--inline" for a in argv):
        sys.exit(__doc__)
    reviews = load_reviews()
    if scopes and scopes[0] not in reviews:
        sys.exit(f"error: no review for `{scopes[0]}`")
    for scope in scopes or reviews:
        for f in reviews[scope]["files"]:
            old = f.read_text(encoding="utf-8")
            new = to_inline(old) if inline else to_references(old, f)
            if new != old:
                f.write_text(new, encoding="utf-8")
            n = len(link_definitions(new))
            print(f"review-refs: {f.relative_to(LIBRARY_ROOT)}: {n} link definitions"
                  + ("" if new != old else " (unchanged)"))


if __name__ == "__main__":
    main(sys.argv[1:])
